// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCiWxmgn2DQaF-xMj5ASidY2RpwCBr6ISE',
//     appId: '1:960284070756:web:73e2a9e4139f48e6c7a071',
//     messagingSenderId: '960284070756',
//     projectId: 'airbnb-60a32',
//     authDomain: 'airbnb-60a32.firebaseapp.com',
//     storageBucket: 'airbnb-60a32.firebasestorage.app',
//     measurementId: 'G-0JNVP3BLJF',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCQL6MvNnpW5LBdMEGFEcYkKveWGE47Na0',
//     appId: '1:960284070756:android:63ef4975b720f1dcc7a071',
//     messagingSenderId: '960284070756',
//     projectId: 'airbnb-60a32',
//     storageBucket: 'airbnb-60a32.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA7pSb6LFZxO8F1_lthISeQ4TF0potXCww',
//     appId: '1:960284070756:ios:2c87091a759d894ec7a071',
//     messagingSenderId: '960284070756',
//     projectId: 'airbnb-60a32',
//     storageBucket: 'airbnb-60a32.firebasestorage.app',
//     androidClientId: '960284070756-sf28e2n7q9kcqeshadl3ec5dp4rlkmf7.apps.googleusercontent.com',
//     iosClientId: '960284070756-5svkbile0d4qapidsb2jblo8lnsrcr0e.apps.googleusercontent.com',
//     iosBundleId: 'com.example.qaren',
//   );
// }
